version: "3.8"
services:
  wsei_backend:
    image: "wsei_backend"
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    deploy:
      mode: replicated
      replicas: 0
  pma:
    image: "phpmyadmin"
    environment:
      - PMA_PORT=3306
      - PMA_HOST=database
    depends_on:
      - database
    ports:
      - "8081:80"
    networks:
      - inet
    hostname: "pma"
  database:
    build: "./backend/database"
    env_file:
      - "./backend/database/.env"
    ports:
      - "3306:3306"
    networks:
      - inet
    hostname: "database"
  cerber:
    build: "./backend/cerber"
    env_file:
      - "./backend/cerber/.env"
    environment:
      - DOCKER=1
    depends_on:
      - wsei_backend
      - database
    ports:
      - "3001:3001"
    networks:
      - inet
    hostname: "cerber"
  athena:
    build: "./backend/athena"
    env_file:
      - "./backend/athena/.env"
    environment:
      - DOCKER=1
    depends_on:
      - wsei_backend
      - database
    ports:
      - "3002:3002"
    networks:
      - inet
    hostname: "athena"

networks:
  inet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
