#!/bin/bash
set -e

mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL

CREATE USER 'cerber'@'%' IDENTIFIED WITH caching_sha2_password BY '$CERBER_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON cerber.* TO 'cerber'@'%';
ALTER USER 'cerber'@'%';
ALTER USER 'cerber'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

CREATE USER 'athena'@'%' IDENTIFIED WITH caching_sha2_password BY '$ATHENA_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON athena.* TO 'athena'@'%';
ALTER USER 'athena'@'%';
ALTER USER 'athena'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

EOSQL
